### PR TITLE
Root package.json scripts

### PR DESCRIPTION
**Pull request by lupus117**
# Adds scripts and root package.json, with only scripts section

## Scripts added

1.  "install-dep" installs front end and back end dependencies
2.  "dockerup" starts all docker profiles
3.  "fe" starts front end docker
4.  "be" starts back end docker
5.  "make-env" copies both .env files 
6.  "dockerdown" takes down dockers
7.  "start" runs 5. -> 1. -> 2 .

### CODE REVIEW

**Comment by Orzelius** [comment]
I don't think this should be a package.json file as the root folder is not node a node module nor a package so it makes no sense to have a package.json file. Yesterday I advertised Makefiles, I think they are used way more often for tasks like this and also are suited for the problem at hand

**Comment by Kasparsu** [comment]
> I don't think this should be a package.json file as the root folder is not node a node module nor a package so it makes no sense to have a package.json file. Yesterday I advertised Makefiles, I think they are used way more often for tasks like this and also are suited for the problem at hand

I am not sure about make files because their main use is to "MAKE" stuff build etc. I would say good sh file would be in order. Windows users that dont use bash can go download bash or commit their own .BAT files alternatively comandline apps are not hard. make an executable js file as whole project requires node anyway. Node has nice exec function and you can use one or 2 libraries to make it cool and stuff with --help and hints. https://www.npmjs.com/package/commander . this could be done in separate project and then built and dist added here.

**Comment by Orzelius** [comment]
> because their main use is to "MAKE" stuff build etc.

Idk about that. At work most projects use make-files for stuff like this but maybe it's just my company's thing. Usually on projects similar to this there are commands available like `make fe` or `make run` or `make run:prod` (runs only fe against prod) or `make k8s_sh` which connects to one of the k8s instances in the context your shell is currently in and etc.

I see makefiles like sh files, but with more functionality.

**Comment by Orzelius** [comment]
Closing to reduce clutter. Feel free to reopen if somebody feels like continuing.

**Pull request closed without merging**
