### PR TITLE
Add backend lint and build jobs to travisCI

### PR DESCRIPTION
**Pull request by OskarSchamardin**
Closes issue: #51

### CODE REVIEW

**Comment by Orzelius** [comment]
Please make this a draft pr until you get it working. Currently you are not installing dependencies. Also the be and fe part can run at the same time to save time

**Comment by OskarSchamardin** [comment]
> Please make this a draft pr until you get it working. Currently you are not installing dependencies. Also the be and fe part can run at the same time to save time

Fixed in c9e5483f009f19a3a5dd79b38a637e60833c7aec

**Comment by Orzelius** [comment]
I think currently everything can run in parallel. There's no need to wait for the fe to finish before starting with be. Read more about parallel jobs here: https://docs.travis-ci.com/user/build-stages/

Only once we get to the deploy part we need for the both build stages to be finished but currently they can run completely in parallel/simultaneously.

**Comment by Orzelius** [comment]
And also I think the jobs should also fail on lint warnings as well
@Erikyy wdyt?

**Comment by OskarSchamardin** [comment]
> I think currently everything can run in parallel. There's no need to wait for the fe to finish before starting with be. Read more about parallel jobs here: https://docs.travis-ci.com/user/build-stages/
> 
> Only once we get to the deploy part we need for the both build stages to be finished but currently they can run completely in parallel/simultaneously.

Fixed in commit: 9c0f12b3052c68d872b2255a4e52d3a2c9f31bbe.
There are now 3 stages: npm dependencies, lint and build. FE and BE are both handled in parallel. This can be optimized further at the expense of combining lint and build stages, but I don't think it's nessecary.

**Review by Kasparsu — APPROVED** [review]

**Review by Orzelius — APPROVED** [review]

**Pull request merged**
